apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  labels:
    type: local
spec:
  storageClassName: {{ .Values.postgres.volume.storageClass }}
  capacity:
    storage: {{ .Values.postgres.volume.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
